export const lancamentos = [
    {
      id: 1,
      title: "Salário",
      type: "receita",
      amount: 2500.0,
      date: "2024-12-05",
      category: "Renda fixa",
      frequencia: "mensal",
      parcelas: 0,
      conta: "Salário",
    },
    {
      id: 2,
      title: "Venda de Produto",
      type: "receita",
      amount: 1200.5,
      date: "2024-12-10",
      category: "Vendas",
      frequencia: "única",
      parcelas: 0,
      conta: "Venda de Produto",
    },
    {
      id: 3,
      title: "Aluguel",
      type: "despesa",
      amount: 1500.0,
      date: "2024-12-01",
      category: "Moradia",
      frequencia: "mensal",
      parcelas: 0,
      conta: "Aluguel",
    },
    {
      id: 4,
      title: "Supermercado",
      type: "despesa",
      amount: 350.75,
      date: "2024-12-07",
      category: "Alimentação",
      frequencia: "única",
      parcelas: 0,
      conta: "Supermercado",
    },
    {
      id: 5,
      title: "Transporte",
      type: "despesa",
      amount: 200.0,
      date: "2024-12-05",
      category: "Transporte",
      frequencia: "mensal",
      parcelas: 0,
      conta: "Transporte",
    },
    {
      id: 6,
      title: "Parcelamento de Celular",
      type: "despesa",
      amount: 500.0,
      date: "2024-12-01",
      category: "Parcelado",
      frequencia: "parcelado",
      parcelas: 12,
      conta: "Parcelamento Celular",
    },
    {
      id: 7,
      title: "Salário Extra",
      type: "receita",
      amount: 800.0,
      date: "2024-12-15",
      category: "Renda variável",
      frequencia: "única",
      parcelas: 0,
      conta: "Salário Extra",
    },
    {
      id: 8,
      title: "Conta de Luz",
      type: "despesa",
      amount: 150.0,
      date: "2024-12-10",
      category: "Utilidades",
      frequencia: "mensal",
      parcelas: 0,
      conta: "Conta de Luz",
    },
  ];